import type { Metadata } from "next";
import Image from "next/image";
import { ContactEnquiryCards } from "@/components/contact-enquiry-cards";
import styles from "../contact.module.css";
export const metadata:Metadata={title:"Contact",description:"Contact OSANO to discuss a solution for your context.",alternates:{canonical:"/contact"}};
export default function ContactPage(){return <div className={styles.page}>
  <section className={styles.hero}><div className={styles.heroMedia}><Image src="/images/contact/contact-hero.webp" alt="OSANO consultation in a calm living environment" fill priority sizes="100vw"/></div><div className={styles.heroCopy}><p className={styles.eyebrow}>ABOUT OSANO</p><h1>Contact and<br/>Consultation</h1><p>Speak with OSANO about a living environment that supports everyday well-being.</p><a href="#contact-form">Start your enquiry&nbsp; →</a></div></section>
  <section className={styles.enquirySection}><h2>How can we help?</h2><ContactEnquiryCards/></section>
  <section className={styles.formSection} id="contact-form"><div className={styles.formIntro}><h2>We’re<br/>here to<br/>help.</h2><p>Complete the form and our team will review your enquiry and connect you with the right person to assist.</p><strong>ALL FIELDS MARKED WITH * ARE REQUIRED.</strong></div><form className={styles.form} action="mailto:jdproduct2020@gmail.com" method="post" encType="text/plain"><div className={styles.twoColumns}><label>Full Name *<input name="name" type="text" placeholder="Enter your name" required/></label><label>Email *<input name="email" type="email" placeholder="jane@example.com" required/></label><label>Phone *<input name="phone" type="tel" placeholder="+66 XX XXX XXXX" required/></label><fieldset><legend>Preferred Contact Method *</legend><div className={styles.radios}><label><input type="radio" name="contact-method" value="email" defaultChecked/> Email</label><label><input type="radio" name="contact-method" value="phone"/> Phone</label><label><input type="radio" name="contact-method" value="line"/> LINE</label><label><input type="radio" name="contact-method" value="other"/> Other</label></div></fieldset></div><label>Topic *<select name="topic" defaultValue="" required><option value="" disabled>Please select a topic</option><option>General Enquiry</option><option>Solution Consultation</option><option>Business & Dealer Enquiry</option><option>Customer Support</option></select></label><label>Business / Environment Type<input name="environment" type="text" placeholder="e.g., Home, Office, Wellness Space"/></label><label>Message *<textarea name="message" rows={5} placeholder="Tell us more about your enquiry..." required/></label><label className={styles.consent}><input type="checkbox" required/><span>I agree to OSANO’s Privacy Policy and consent to being contacted regarding my enquiry.</span></label><button type="submit">Submit enquiry</button></form></section>
  <section className={styles.reachSection}><h2>Other ways to reach us</h2><div className={styles.simpleReach}><a href="mailto:jdproduct2020@gmail.com"><small>EMAIL</small><b>jdproduct2020@gmail.com</b></a><div><small>PHONE</small><b>02-952-5414</b><b>066-125-6694 (Sales)</b><b>089-458-5177 (Customer Service)</b></div><a href="https://line.me/R/ti/p/@osano" target="_blank" rel="noreferrer"><small>LINE OFFICIAL ACCOUNT</small><b>@osano</b></a><div><small>SOCIAL MEDIA</small><b><a href="https://www.facebook.com/share/1ETv9gkpym/?mibextid=wwXIfr">Facebook</a></b><b><a href="https://www.instagram.com/osano_official">Instagram</a></b><b><a href="https://www.tiktok.com/@osanofficial">TikTok</a></b></div></div></section>
  <section className={styles.mapSection}><div className={styles.mapCopy}><p>VISIT US BY APPOINTMENT</p><h2>Visit the<br/>Consultation Studio</h2><span>We welcome visits by appointment to experience our solutions and speak with our consultants.</span><a href="#contact-form">Request appointment&nbsp; →</a><small>Visits by appointment only. Location details will be provided upon confirmation.</small></div><iframe title="OSANO location on Google Maps" src="https://www.google.com/maps?q=OSANO%20Bangkok%20Thailand&output=embed" loading="lazy" referrerPolicy="no-referrer-when-downgrade"/></section>
</div>}
