"use client";
import Image from "next/image";
import { useState } from "react";
import styles from "@/app/technology.module.css";
import { Molecule3D } from "@/components/molecule-3d";

const steps = [
  { key:"Principle", title:"Principle: How the Technology Works", copy:"Every technology starts with a core scientific principle. This layer explains how it works, from its fundamental properties to real-world applications.", points:["Core scientific principles and key reactions explained clearly.","Key properties and molecular behaviours under everyday environmental conditions."] },
  { key:"Application", title:"Application: From Science to Everyday Life", copy:"The scientific principle becomes useful when it responds to real needs in health, hygiene and living environments.", points:["Practical uses are considered within real routines and environments.","Each application connects the technology to a clear everyday benefit."] },
  { key:"Format", title:"Format: Choosing the Right Experience", copy:"Different formats make each technology suitable for different spaces, routines and desired outcomes.", points:["The delivery format is matched to the intended use and environment.","Products make advanced science simple to experience."] },
];
const applications = [
  { label:"OSANO Hygiene", title:"Smarter everyday hygiene with Aqueous Ozone", copy:"Explore how Aqueous Ozone can be applied across everyday hygiene needs, from surfaces and food preparation to water-related applications.", tags:["Surface Spray","Food Preparation","Air Hygiene"], image:"/images/technology/technology-hygiene.webp" },
  { label:"OSANO Health", title:"Everyday well-being supported by thoughtful science", copy:"Discover how oxygen and hydrogen technologies can support comfortable routines, hydration and everyday vitality.", tags:["Daily Vitality","Hydration","Recovery"], image:"/images/technology/technology-health.webp" },
  { label:"OSANO Pets", title:"Better environments for life with pets", copy:"Explore practical technologies designed to support cleaner, calmer and more comfortable shared spaces for people and pets.", tags:["Shared Spaces","Comfort","Everyday Care"], image:"/images/technology/technology-pet.webp" },
];

export function TechnologySteps(){const [index,setIndex]=useState(0);const active=steps[index];return <><div className={styles.tabs} role="tablist">{steps.map((step,i)=><button type="button" key={step.key} className={i===index?styles.activeTab:undefined} onClick={()=>setIndex(i)} role="tab" aria-selected={i===index}>{i+1}. {step.key}</button>)}</div><div className={styles.principleGrid}><div className={styles.moleculeStage}><Molecule3D/></div><div className={styles.principleCopy} key={active.key}><h3>{active.title}</h3><p>{active.copy}</p><ul>{active.points.map(point=><li key={point}>{point}</li>)}</ul></div><aside><small>YOU ARE VIEWING</small><strong>{active.key}</strong><p>{active.copy}</p></aside></div></>}
export function TechnologyApplications(){const [index,setIndex]=useState(0);const active=applications[index];return <div className={styles.applicationExperience}><div className={styles.applicationTabs} role="tablist">{applications.map((item,i)=><button type="button" key={item.label} className={i===index?styles.activeApplication:undefined} onClick={()=>setIndex(i)} role="tab" aria-selected={i===index}><small>0{i+1}</small><span>{item.label}</span><b aria-hidden="true">↗</b></button>)}</div><article className={styles.applicationCard} key={active.label}><div className={styles.applicationMedia}><Image src={active.image} alt={`${active.label} practical application`} fill sizes="(max-width:700px) 100vw,58vw" /></div><div className={styles.applicationContent}><p>{active.label}</p><h3>{active.title}</h3><span>{active.copy}</span><div className={styles.tags}>{active.tags.map(tag=><span key={tag}>{tag}</span>)}</div><button className={styles.animatedCta} type="button"><span>Explore {active.label.replace("OSANO ","")}</span></button></div></article></div>}
